# Generated by Django 5.2.1 on 2025-09-10 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['title', 'is_publicate', 'created_at', 'views_counter'], 'permissions': [('can_unpublish_product', 'Can unpublish product')], 'verbose_name': 'статья', 'verbose_name_plural': 'статьи'},
        ),
    ]
