# Generated by Django 5.2.1 on 2025-09-11 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['title', 'is_publicate', 'created_at', 'views_counter'], 'verbose_name': 'статья', 'verbose_name_plural': 'статьи'},
        ),
    ]
