# Generated by Django 5.2.1 on 2025-09-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_publicate',
            field=models.BooleanField(default=False, verbose_name='Опубликовать'),
        ),
    ]
